### ISSUE TITLE
Error while initilizing the api

### ISSUE THREAD

**Issue by TheSilentPro** [stanjg/Ptero4J#16]
After a long time getting maven to work and compiling a version of the API i got the JAR.
But now im trying to create something and when doing this

code: https://hastebin.com/ovoxuzunoc.cpp

error: https://hastebin.com/vevahemoxe.bash

**Comment by stanjg** [comment]
OkHttp is not being loaded as a dependency, are you sure your dependencies are right?

Please post your `pom.xml` file.

**Comment by TheSilentPro** [comment]
I am using a compiled JAR, maybe that's corrupt or something. I've never used maven before this is my first time.
This is the pom.xml from the jar: https://hastebin.com/oqiyasemit.xml

**Comment by stanjg** [comment]
Remove the dependencies block you currently have and replace it with this:

```
    <repositories>
        <!-- Jitpack repo -->
        <repository>
            <id>jitpack</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    
    <dependencies>
        <!-- Panel API -->
        <dependency>
            <groupId>com.github.stanjg</groupId>
            <artifactId>Ptero4J</artifactId>
            <version>master-SNAPSHOT</version>
        </dependency>
    </dependencies>```
Then reimport your dependencies using maven and it should be working fine.
