### ISSUE TITLE
Starting servers via the API

### ISSUE THREAD

**Issue by TheAimWolf** [stanjg/Ptero4J#20]
Hello,
I have a question. I want to use the API as a admin-tool. So I tried to add a function which could start the servers:
(Server.java, package: com.stanjg.ptero4.entities.panel.admin)
`public boolean start() {

        JSONObject test;
        test = new JSONObject();
        test.put("signal", "start");
        System.out.println(test);
        return new GenericAdminAction(api, "/servers/"+this.shortId+"/power", HTTPMethod.POST, test).execute() == 204;
    }`
But the console returns an warning and the server doesn't start:
`An invalid request was made by the library, please create an issue on github.
POST https://control.junico.de/api/application/servers/8/power`

I saw that you have to transmit a parameter to the server via the url so that the server know what poweraction you want to perform: [https://dashflo.net/docs/api/pterodactyl/v0.7/#send-power-action](url)

Now my question is: Is it possible to send poweractions with this API or what have I done wrong?
Sorry for my bad english.

I hope anyone can help me out with this. If you need any more informations just tell me.
I whish you all a beautiful day.

TheAimWolf

**Comment by stanjg** [comment]
Ptero4J already has a built-in feature for this. However it’s located in the client API as it’s also located in the client API of the panel. 

It’s documented right here: https://github.com/stanjg/Ptero4J/blob/master/README.MD#userservers-actions

If you use a client API key that belongs to an admin account you can still control all servers.

**Comment by TheAimWolf** [comment]
Thank you so much. Sorry, i have stopped reading the documentation to fix the problem. Thank you for your awesome API and your quick reply😉👍🏻
