### ISSUE TITLE
[Suggestion] Get console log from server

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [stanjg/Ptero4J#6]
It would be great if it would be possible to get the current console log as an string or an string array.

I think about something like this:
```java
int logLines = 2;
String[] logList = userServer.getLogAsList(logLines);
//Output: {"Player234 joined the game","<Player234> Hi"}

String log = userServer.getLogAsString(logLines);
//Output: "Player234 joined the game\n<Player234> Hi"

```

**Comment by stanjg** [comment]
This is not possible with the current Pterodactyl API. You could make a request to the daemon API manually, but this is not something I am going to implement in Ptero4J.

**Comment by Blackbalrog** [comment]
Hello,

I am French and I wanted to know if you had managed to recover the console?
Because I'm trying to do the exact same thing but I don't know how to go about it: /
