### ISSUE TITLE
Probably an update caused the API fully unusable

### ISSUE THREAD

**Issue by sorbanbela** [stanjg/Ptero4J#8]
Hey.

First of all, i really appreciate this project. A really good idea, and would be very useful if you make it working.
So now, i'm trying to use it first time and found the issue
`Exception in thread "main" org.json.JSONException: JSONObject["databases"] is not an int.` when tried to get a server's name from userServersController.

Probably the code isn't working with the latest version of Pterodactyl panel, there was a huge API update, everything changed. For the reasons mentioned above, I do not think the code will work at all.

Hope you enjoy coding, and will fix it as you can.

**Comment by ErdbeerbaerLP** [comment]
I also had the problem one time with the [demo panel](https://demo.pterodactyl.io/). But it worked later...

**Comment by sorbanbela** [comment]
UPDATE:
The issue is not caused by PteroAPI update, but if you have not set up the database count for a server (meaning unlimited then) you will get an issue while parsing the JSON object at the feature_limits/databases part. If no value was given in the pterodactyl configuration, then it will be null, and this issue has not been handled correctly, so the whole process will end at this moment.
